base_url = "https://augnun.github.io"      # Domain name of your website
title = "Blog do Augusto"
description = "Um blog de divagações, questões e incertezas."
default_language = "pt"
theme = "apollo"

compile_sass = true

mathjax = true

# highlight_code = true
# highlight_theme = "base16-ocean-dark"

generate_feeds = true
feed_filenames = ["rss.xml"]

taxonomies = [{ name = "tags", feed = true},
              { name = "categories", feed = true }]



[extra]
# theme = "auto"
socials = [
  # Configure socials here
]
menu = [
  { name = "Blog", url = "/blog", weight = 1 },
  { name = "Blogroll", url = "/blogroll", weight = 2 },
  { name = "Posts", url = "/posts", weight = 3 },
  { name = "Projects", url = "/projects", weight = 4 },
  { name = "Sobre", url = "/about", weight = 5 },
  { name = "Loja", url = "/loja", weight = 6},
]

author = "Augusto Nunes"
github = "https://github.com/augnun/"
